ALTER TABLE system_state
  ADD COLUMN IF NOT EXISTS finance_frozen BOOLEAN NOT NULL DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS freeze_reason TEXT,
  ADD COLUMN IF NOT EXISTS last_reconciliation_at TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS last_safe_recovery_at TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS admin_override_enabled BOOLEAN NOT NULL DEFAULT FALSE;
