export const JOBS = {
  AUTO_CANCEL_UNPAID: "auto-cancel-unpaid-orders",
  AUTO_CANCEL_ORDER: "auto-cancel-order",
  AUTO_EXPIRE_RETURN_WINDOW: "auto-expire-return-window",
  AUTO_CLOSE_DISPUTED: "auto-close-disputed",
  RELEASE_RESERVATIONS: "release-reservations",
  RESERVATION_CLEANUP: "reservation-cleanup",
  REFUND_RETURN: "refund-return",
  PROCESS_EVENT: "process-event",
  RECONCILE_PAYMENTS: "reconcile-payments",
  SEND_EMAIL: "send-email",
  RUN_PAYOUTS: "run-payouts",
  FINANCE_RECONCILE: "finance-reconcile",
  FINANCE_RISK_MONITOR: "finance-risk-monitor",
  FINANCE_DIGEST: "finance-digest",
  FINANCE_SAFE_RECOVERY_CHECK: "finance-safe-recovery-check",
  SELLER_RISK_REVALIDATION: "seller-risk-revalidation",
  FINANCE_RISK_SCORING: "finance-risk-scoring",
  FINANCE_ISOLATION_MONITOR: "finance-isolation-monitor",
  NOTIFY_SELLER_RETURN_REQUESTED: "notify-seller-return-requested",
  START_RETURN_WINDOW: "start-return-window",
  DELIVER_NOTIFICATION: "deliver-notification",
  BATCH_NOTIFICATIONS: "batch-notifications",
  CREATE_SHIPMENT: "create-shipment",
  SYNC_SHIPMENT_TRACKING: "sync-shipment-tracking",
  PROCESS_SETTLEMENTS: "process-settlements",
  CREATE_PAYOUT_BATCHES: "create-payout-batches"
} as const;

export type JobName = (typeof JOBS)[keyof typeof JOBS];
